main: fi.natroutter.hubcore.HubCore
name: HubCore
version: 2.0.3
author: NATroutter
description: Core plugin for all hub servers
api-version: 1.18
website: https://NATroutter.fi
depend: [NATLibs]
softdepend:
  - PlaceholderAPI
  - Citizens
  - BetterParkour

